name = "Trading Bot"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "ce0phpztqw2zv3g7v3h7z6q5"
  title = "Апи ордеров"
  description = "<p>Создать апи запросы для размещения, изменения и закрытия ордеров</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "r83t0gvht4snrqce09tqpf8g"
    title = "Размещение ордеров"
    completed = false

    [[processes.tasks.checkList]]
    id = "g9xt7advksusyvbylrswpaw5"
    title = "Закрытие ордеров"
    completed = false

    [[processes.tasks.checkList]]
    id = "s9xwcsy6yz18v1o7cykdx3og"
    title = "Изменение тейк-профита"
    completed = false

    [[processes.tasks.checkList]]
    id = "i3b3abhnmgrjkxgk74g3hsff"
    title = "Размещение тейк-профита"
    completed = false

  [[processes.tasks]]
  id = "hf7yb9xenq76bh7n7htyvvmf"
  title = "Написать программу для синхронизации ДФ на ТФ 15 и ТФ 60"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "hkotn7roy04143mbno2vubfd"
  title = "Создать индикатор полос боллинджера"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "qihtok1xgzkrymt62n1g90y8"
  title = "Создать сеточный индикатор"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "odhego5towzvpizevo740z41"
  title = "Загрузить исторические данные для стратегии"
  description = "Загрузить данные с ТФ 15 и ТФ 60"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "kwxvdgqsma8spo52djcwcfkj"
name = "Testing"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "jskb13ena471gjaaxl999uuw"
  title = "Баланс монеты и долларов"
  description = "<p>Получить баланс через апи</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "vbqm34oxmx3mop3l514linmd"
    title = "Баланс в биткоинах"
    completed = true

    [[processes.tasks.checkList]]
    id = "pf3dekosuc7ai3mv76tk9j51"
    title = "Баланс в долларах"
    completed = true

  [[processes.tasks]]
  id = "i8hp7x3onmt5ol1gi91nuf33"
  title = "Получение рыночных данных"
  description = "<p>Реализовать класс с апи запросами к бирже для получения рыночных данных с определнного ТФ и определенного количества</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "h2hzc1j3y5kpy4sxv6357ly2"
    title = "Написать запрос получения сырых данных"
    completed = true

    [[processes.tasks.checkList]]
    id = "xw0xzv14ygp68a1lpuz3h7zw"
    title = "Обработчик сырых данных"
    completed = true

  [[processes.tasks]]
  id = "ptf21efyaj58fnjh2ectjuqn"
  title = "Загрузка исторических данных"
  description = "Написать скрипт для загрузки исторических данных с любого ТФ"
  tag = "backlog"
  linkFiles = [ "/backend/containers.py" ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
